#!/bin/bash

repoList=( $CIRCLE_REVERSE_DEPENDENCIES )
# repoList=()

for repo in "${repoList[@]}"
do
  echo Triggering CI build $repo
  curl --header "Content-Type: application/json" \
    -d "{\"branch\":\"${CIRCLE_BRANCH}\"}" \
    -X POST "https://circleci.com/api/v1.1/project/github/redsift/${repo}/build?circle-token=${CIRCLE_TOKEN}"
done
