version: 2.1

executors:
  dockexec:
    shell: /bin/sh
    environment:
      CONTAINER_NAME: quay.io/redsift/sandbox
      CIRCLE_REVERSE_DEPENDENCIES: sandbox-javascript sandbox-python sandbox-java sandbox-julia sandbox-go sandbox-swift
    docker:
      - image: docker:18.09.3


commands:
  commonbuild:
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t sandbox .
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
  tagging:
    parameters:
      tag:
        type: string
      beta:
        type: boolean
        default: true
    steps:
      - run: echo "Tagging as $CONTAINER_NAME:<< parameters.tag >>" 
      - run: docker tag sandbox:latest "$CONTAINER_NAME:"<< parameters.tag >><<# parameters.beta >>-beta<</ parameters.beta >>

jobs:
  build:
    executor: dockexec
    steps:
      - commonbuild
      - tagging:
          tag: "17.10"
      - deploy:
          command: docker push quay.io/vchris1416/sandbox

  build-release:
    executor: dockexec
    steps:
      - commonbuild
      - tagging:
          tag: "17.10"
          beta: false
      - tagging:
          tag: "latest"
          beta: false

  trigger-builds:
    executor: dockexec
    steps:
      - checkout
      - run: 
          shell: /bin/bash
          command: ./circle_ci_trigger_build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /release-.*/
      - trigger-builds:
          requires:
            - build
      - build-release:
          filters:
            branches:
              only:
                - /release-.*/
