version: 2.1

default:
  environment: &envvars
    CONTAINER_NAME: quay.io/redsift/sandbox
    CIRCLE_REVERSE_DEPENDENCIES: sandbox-javascript sandbox-python sandbox-java sandbox-julia sandbox-go sandbox-swift

executors:
  dockexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/docker:19.03.5

  baseexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/base:2019.03


commands:
  commonbuild:
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t sandbox .
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
  tagging:
    parameters:
      tag:
        type: string
    steps:
      - run: echo "Tagging as $CONTAINER_NAME:<< parameters.tag >>"
      - run: docker tag sandbox:latest "$CONTAINER_NAME:"<< parameters.tag >>

jobs:
  build:
    executor: dockexec
    steps:
      - commonbuild
      - tagging:
          tag: "beta"
      - tagging:
          tag: "18.04-beta"
      - deploy:
          command: docker push $CONTAINER_NAME
      - run: ./circle_ci_trigger_build

  build-release:
    executor: dockexec
    steps:
      - commonbuild
      - tagging:
          tag: "18.04"
      - tagging:
          tag: "latest"
      - deploy:
          command: docker push $CONTAINER_NAME
      - run: ./circle_ci_trigger_build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /release-.*/
      - build-release:
          filters:
            branches:
              only:
                - /release-.*/
